#!/bin/sh

### BEGIN INIT INFO
# Provides:          traffic
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Trafficlights
# Description:       Traffic lights
### END INIT INFO

ARGS="-m pia"
DAEMON="/usr/bin/python /home/pi/traffic.py"
PIDFILE="/var/run/traffic.pid"

. /lib/lsb/init-functions

case "$1" in 
    start)
        echo "Starting traffic"
        start-stop-daemon --start --background --oknodo --pidfile $PIDFILE -m --exec $DAEMON -- $ARGS
        ;;
    stop)
        echo "Stopping traffic"
        start-stop-daemon --stop --oknodo --pidfile $PIDFILE
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON
        ;;
    *)
        echo "Usage: /etc/init.d/traffic start|stop|status"
        exit 1
        ;;
esac

exit 0
